USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE EMP_DETAILS_RULES AS
SELECT '^(19|20)([^12]|0[1-9]|1[1-9]|2[1-2])[- \/.](0[1-9]|1[012])[-\/.](0[1-9]|[12][0-9]|3[01])$' REGISTRATION_DTTM,
'[0-9]{1,4}' ID,
'[a-zA-Z]{3,10}' FIRST_NAME,
'[a-zA-Z]{3,15}' LAST_NAME,
'\\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}' EMAIL,
'(MALE|FEMALE|Male|Female)' GENDER,
'^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$' IP_ADDRESS,
'[0-9]+' CC,
'[a-zA-Z]{2,}' COUNTRY,
'^(19|20)([^12][0-9]|0[1-9]|1[1-9]|2[1-2])[- \/.](0[1-9]|1[012])[-\/.](0[1-9]|[12][0-9]|3[01])$' BIRTHDAY,
'[0-9]{2,6}[.][0-9]{2}' SALARY,
'[a-zA-Z]+\s[a-zA-Z]+' TITLE,
'.*' COMMENTS,
'.*' DATA_SOURCE;

CREATE OR REPLACE TABLE EMP_DETAILS_MATRIX
AS
SELECT 
A.ID SRC_ID,
CASE 
WHEN A.REGISTRATION_DTTM RLIKE B.REGISTRATION_DTTM = TRUE
THEN 1 ELSE 0
END REGISTRATION_DTTM,

CASE 
WHEN A.ID RLIKE B.ID = TRUE
THEN 1 ELSE 0
END ID,

CASE 
WHEN A.FIRST_NAME RLIKE B.FIRST_NAME = TRUE
THEN 1 ELSE 0
END FIRST_NAME,

CASE 
WHEN A.LAST_NAME RLIKE B.LAST_NAME = TRUE
THEN 1 ELSE 0
END LAST_NAME,

CASE 
WHEN A.EMAIL RLIKE B.EMAIL = TRUE
THEN 1 ELSE 0
END EMAIL,

CASE 
WHEN A.GENDER RLIKE B.GENDER = TRUE
THEN 1 ELSE 0
END GENDER,

CASE 
WHEN A.IP_ADDRESS RLIKE B.IP_ADDRESS = TRUE
THEN 1 ELSE 0
END IP_ADDRESS,

CASE 
WHEN A.CC RLIKE B.CC = TRUE
THEN 1 ELSE 0
END CC,

CASE 
WHEN A.COUNTRY RLIKE B.COUNTRY = TRUE
THEN 1 ELSE 0
END COUNTRY,

CASE 
WHEN TO_CHAR(TRY_TO_DATE(A.BIRTHDATE),'YYYY-MM-DD') RLIKE B.BIRTHDAY = TRUE
THEN 1 ELSE 0
END BIRTHDAY,

CASE 
WHEN A.SALARY RLIKE B.SALARY = TRUE
THEN 1 ELSE 0
END SALARY,

CASE 
WHEN A.TITLE RLIKE B.TITLE = TRUE
THEN 1 ELSE 0
END TITLE,

CASE 
WHEN A.COMMENTS RLIKE B.COMMENTS = TRUE
THEN 1 ELSE 0
END COMMENTS,

CASE 
WHEN A.DATA_SOURCE RLIKE B.DATA_SOURCE = TRUE
THEN 1 ELSE 0
END DATA_SOURCE

FROM 
EMP_DETAILS A
CROSS JOIN
EMP_DETAILS_RULES B;

INSERT INTO TABLE_SCORES 
select 'EMP_DETAILS' TABL_NAME,round(sum(record_score)/1000,2) tbl_score,CURRENT_DATE() SCORED_DATE FROM
(
select
(REGISTRATION_DTTM+id+first_name+last_name+email+gender+ip_address+cc+country+birthday+salary+title+comments+data_source)/14 record_score
from EMP_DETAILS_MATRIX
)
